spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000

logging:
  level:
    com.example.debounce: debug
    org.springframework.data.redis: info

server:
  port: 8080
  servlet:
    context-path: /