server:
  port: 8080

spring:
  application:
    name: url-debounce
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

debounce:
  urls:
    "/api/submit":
      time: 2000
      message: "提交太频繁，请稍后再试"
      enabled: true
    "/api/upload/*":
      time: 5000
      message: "上传太频繁，请稍后再试"
      enabled: true